name: randomness_testing
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  grizzly_distuv:
    git:
      url: https://github.com/Grizzly-dart/grizzly_distuv.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0